### ISSUE TITLE
Windows SDK not found while compiling. 

### ISSUE THREAD

**Issue by Lucas3Dspain** [Autodesk/Aurora#1]
I'm trying to compile in windows 10 with visual studio 2019. I have installed the windows SDK  10.0.22621.0 
 but I get this error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at Libraries/Aurora/CMakeLists.txt:11 (message):
    Windows SDK version  is found but version 10.0.22000.0 or later is required.
    Windows SDK version 10.0.22000.0 or later can be installed from https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/	Aurora	C:\Users\LucasMorante\Desktop\_Repos\Aurora\Libraries/Aurora/CMakeLists.txt	11	
```

It is weird that it does not show me any windows SDK version.

```
    set(MINIMUM_WINDOWS_SDK_VERSION "10.0.22000.0")
    if(WINDOWS_SDK_VERSION VERSION_LESS MINIMUM_WINDOWS_SDK_VERSION)
        message(FATAL_ERROR
                "  Windows SDK version ${WINDOWS_SDK_VERSION} is found but version ${MINIMUM_WINDOWS_SDK_VERSION} or later is required.\n"
                "  Windows SDK version ${MINIMUM_WINDOWS_SDK_VERSION} or later can be installed from https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/"
        )
```

This is the command I'm using.

`python "%USERPROFILE%/Desktop/_Repos\Aurora\Scripts\installExternals.py" "%USERPROFILE%/Desktop/_Repos/Aurora_externals" --generator  "Visual Studio 16 2019"`

 I might have something wrong in my VS configuration but I don't find what could it be. Any help is welcomed.

**Comment by melMass** [comment]
It clearly states the SDK you are missing [10.0.22000.0]( https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/)

**Comment by gareth-morgan-autodesk** [comment]
Hi @Lucas3Dspain do you have no Windows SDK installed at all? That would explain the error message.  Aurora requires at least Windows SDK 10.0.22000.0

**Comment by gareth-morgan-autodesk** [comment]
We use the registry key Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Kits\Installed Roots to find the SDK version.  Which should be set by the Windows Kits installer.  Does your machine not have that registry key set?  

If not you can set manually by pointing the environment variables WINDOWS_SDK_PATH to point to the folder where the WIndows SDK is installed and WINDOWS_SDK_VERSION to the version number of the Windows SDK you have installed installed.

**Comment by Lucas3Dspain** [comment]
Hi Gareth, I do have the SDK installed and its in the registry.

![regedit_FBHTNwz6gH](https://user-images.githubusercontent.com/25728227/202938729-73b4d11b-d13d-4216-a8b7-47b39368b20e.png)

What is weird to me is that the error I'm getting is not getting any version. This variable is not getting any value ${WINDOWS_SDK_VERSION}

**Comment by Lucas3Dspain** [comment]
closed by accident

**Comment by Lucas3Dspain** [comment]
setting manually the environment variables WINDOWS_SDK_PATH, WINDOWS_SDK_VERSION  worked!
