### ISSUE TITLE
"mismatch detected" building Debug version

### ISSUE THREAD

**Issue by ohmaya** [Autodesk/Aurora#10]
cmake --build Build --config Debug

  Aurora.vcxproj -> E:\dp\Sft\GDev\ADSK\Aurora\Build\bin\Debug\Aurora.dll
gtest.lib(gtest-all.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in TestHelpers.obj [E:\dp\Sft\GDev\ADSK\Aurora\Build\Tests\AuroraInternals\AuroraInternalsTests.vcxproj]
gtest.lib(gtest-all.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in TestHelpers.obj [E:\dp\Sft\GDev\ADSK\Aurora\Build\Tests\AuroraInternals\AuroraInternalsTests.vcxproj]
     Creating library E:/dp/Sft/GDev/ADSK/Aurora/Build/lib/Debug/AuroraInternalsTests.lib and object E:/dp/Sft/GDev/ADSK/Aurora/Build/lib/Debug/AuroraInternalsTests.exp
LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library [E:\dp\Sft\GDev\ADSK\Aurora\Build\Tests\AuroraInternals\AuroraInternalsTests.vcxproj]
E:\dp\Sft\GDev\ADSK\Aurora\Build\bin\Debug\AuroraInternalsTests.exe : fatal error LNK1319: 2 mismatches detected [E:\dp\Sft\GDev\ADSK\Aurora\Build\Tests\AuroraInternals\AuroraInternalsTests.vcxproj]
gtest.lib(gtest-all.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in TestHelpers.obj [E:\dp\Sft\GDev\ADSK\Aurora\Build\Tests\Aurora\AuroraTests.vcxproj]
gtest.lib(gtest-all.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in TestHelpers.obj [E:\dp\Sft\GDev\ADSK\Aurora\Build\Tests\Aurora\AuroraTests.vcxproj]
LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library [E:\dp\Sft\GDev\ADSK\Aurora\Build\Tests\Aurora\AuroraTests.vcxproj]
E:\dp\Sft\GDev\ADSK\Aurora\Build\bin\Debug\AuroraTests.exe : fatal error LNK1319: 2 mismatches detected [E:\dp\Sft\GDev\ADSK\Aurora\Build\Tests\Aurora\AuroraTests.vcxproj]
gtest.lib(gtest-all.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in TestHelpers.obj [E:\dp\Sft\GDev\ADSK\Aurora\Build\Tests\Foundation\FoundationTests.vcxproj]
gtest.lib(gtest-all.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in TestHelpers.obj [E:\dp\Sft\GDev\ADSK\Aurora\Build\Tests\Foundation\FoundationTests.vcxproj]
LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library [E:\dp\Sft\GDev\ADSK\Aurora\Build\Tests\Foundation\FoundationTests.vcxproj]
E:\dp\Sft\GDev\ADSK\Aurora\Build\bin\Debug\FoundationTests.exe : fatal error LNK1319: 2 mismatches detected [E:\dp\Sft\GDev\ADSK\Aurora\Build\Tests\Foundation\FoundationTests.vcxproj]
  Plasma.vcxproj -> E:\dp\Sft\GDev\ADSK\Aurora\Build\bin\Debug\Plasma.exe
LINK : fatal error LNK1104: cannot open file 'tbb_debug.lib' [E:\dp\Sft\GDev\ADSK\Aurora\Build\Libraries\HdAurora\hdAurora.vcxproj]

I cannot find "_ITERATOR_DEBUG_LEVEL" in the VS solution.

**Comment by ohmaya** [comment]
> please check if you link to a gtest debug version. This error is typical for mixing debug and release libs.

Basically, I was following https://github.com/Autodesk/Aurora#building-aurora in 2 passes, 1st with Release, then with Debug.

**Comment by ohmaya** [comment]
Cleaned AuroraExternals and Aurora\Build and it works.

**Comment by andy-shiue-autodesk** [comment]
Closed as issue is solved with clean rebuild.

**Comment by ohmaya** [comment]
> Build-debug\ and Build-release

This might affect [deployHdAurora.py](https://github.com/Autodesk/Aurora/blob/main/Scripts/deployHdAurora.py)?
