### ISSUE TITLE
1 RenderIndex can be tied to 1 or multiple RenderDelegates?

### ISSUE THREAD

**Issue by ohmaya** [Autodesk/Aurora#12]
https://graphics.pixar.com/usd/files/Siggraph2019_Hydra.pdf, page 12 says mulitple.

renderIndex.h says single HdRenderDelegate.

**Comment by pixnblox** [comment]
That is a good point, and I believe the code documentation is correct for now, and the presentation is out of date. Specifically, `GetRenderDelegate` states:

> Currently, a render index only supports connection to one type of render delegate, due to the inserted information and change tracking being specific to that delegate type.
