### ISSUE TITLE
"The directory name is invalid" when using deployHdAurora.py for USD building

### ISSUE THREAD

**Issue by oumad** [Autodesk/Aurora#13]
The script `deployHdAurora.py` fails at the step where it tries to build USD, it throws the error : 
```
- Building USD.
Traceback (most recent call last):
  File "Scripts/deployHdAurora.py", line 82, in <module>
    if(subprocess.run(["python", "./build_scripts/build_usd.py", "--python", args.usd_root], cwd=usd_repo_root).returncode != 0):
  File "C:\Users\Mohamed\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Mohamed\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Mohamed\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
NotADirectoryError: [WinError 267] The directory name is invalid
```
When looking at all the paths provided to the `subprocess` function, I found that the issue is with the USD repo, in my case the repo directory is named this way (with all the build steps I followed initially) : `C:\dev\AuroraExternals\src\USD-22.08-Aurora-v22.11`, while [the line 64 in deployHdAurora.py ](https://github.com/Autodesk/Aurora/blob/main/Scripts/deployHdAurora.py#L64) has this : 
```py
usd_repo_root = os.path.join(externals_folder, "src", "USD")
```
Which produces a path like this : `C:\dev\AuroraExternals\src\USD`. So I had to change that line this way for the script to work for me : 
```py
usd_repo_root = os.path.join(externals_folder, "src", "USD-22.08-Aurora-v22.11")
```
Is there a way to better generalize this in the script as opposed to hard coding the USD version ? or maybe it's not an issue I should've faced? I'll gladly submit a PR too if needed.

**Comment by andy-shiue-autodesk** [comment]
This issue should be fixed in v22.12.  There are some big changes in how the externals are built. You would need to have a clean run of `installExternals.py` (i.e. remove the old externals and run the script again). Changes of the build steps were updated in `README.md` . Let us know if you run into any issues.
