### ISSUE TITLE
Missing denoiser files in DirectX implementation

### ISSUE THREAD

**Issue by PaddiM** [Autodesk/Aurora#15]
If ENABLE_DENOISER is true in CMake generating the DirectX solution is not possible:

CMake Error at Libraries/Aurora/CMakeLists.txt:231 (add_library):
  Cannot find source file:

    Source/DirectX/Denoiser.cpp

This file is not in the repository.

Kind regards,

Patrik

**Comment by pixnblox** [comment]
That option is not supported yet... work in progress. 🛠

**Comment by PaddiM** [comment]
Thanks for the info. Let's wait.
