### ISSUE TITLE
can't make a Debug build with v22.12 

### ISSUE THREAD

**Issue by RichardGe** [Autodesk/Aurora#18]
with v22.12 the command:
python Scripts/installExternals.py --build-variant=Debug ExternalDir
has lots of make fails ( with OIIO, USD )

I'm on Windows 10. Working from a clean repo.
on 22.11, I was able to make the Debug build easily.

**Comment by andy-shiue-autodesk** [comment]
I just did a debug build of the externals. Clean clone and clean build, and it built successfully.  
Could you post the errors you got from the build? There should be a log.txt file created by the script when the build fails. You can just attach the log file.  Thanks.

**Comment by RichardGe** [comment]
Thanks for your reply, I'm currently still using 22.11 and it works correctly.
If I need to updated later to 22.12, I'll create a new ticket with more details: log and errors from build.
In the meantime, I'm closing this issue.
