### ISSUE TITLE
Config issue with deployHdAurora.py

### ISSUE THREAD

**Issue by nicelifeBS** [Autodesk/Aurora#2]
There seems to be a config issue with when running the deploy script for hdAurora. It expects the source of USD to be in _src/USD_ but it is actually the name of the zip file which is downloaded with the installDependencies script. And therefore the path is _src/USD-22.08-Aurora-v22.11_

Python traceback:
`Traceback (most recent call last):
  File "Scripts\deployHdAurora.py", line 77, in <module>
    if(subprocess.run(["python","build_scripts/build_usd.py","--python",args.usd_root],cwd=usd_repo_root).returncode!=0):
  File "C:\Users\bjoern\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\bjoern\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\bjoern\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
NotADirectoryError: [WinError 267] The directory name is invalid`

Modifying the deploy script to the correct path fixes this issue.

**Comment by andy-shiue-autodesk** [comment]
The issue should be fixed in v22.12. There are structural changes of the externals so please have a clean run of `installExternals.py` (i.e. remove the old one and re-run the script).
