### ISSUE TITLE
CMake error - Windows 10

### ISSUE THREAD

**Issue by cgrigstd** [Autodesk/Aurora#24]
CMake Error at C:/Program Files/CMake/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Slang (missing: Slang_INCLUDE_DIRS Slang_LIBRARIES)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  Scripts/cmake/modules/FindSlang.cmake:51 (find_package_handle_standard_args)
  Libraries/Aurora/CMakeLists.txt:37 (find_package)
  
  
  I'm using this command to make the build
  cmake -G "Visual Studio 16 2019" -A x64 . -S . -B Build -D EXTERNALS_ROOT=E:\AuroraExternals

**Comment by Lucas3Dspain** [comment]
If you don't mind me asking, how did you fix it? I had the same issue.

**Comment by cgrigstd** [comment]
Hello! @Lucas3Dspain.

Clear! The jargon was not the source of the problem in fact
I changed the version of libpng repo and it works, it has been downloaded and compiled

Originally they are using PNG_URL = "https://github.com/glennrp/libpng/archive/refs/tags/v1.6.29.tar.gz"

I am currently using this version: "https://github.com/glennrp/libpng/archive/refs/tags/v1.6.35.tar.gz" (in my case I am using Windows 10)
You're going to put that link in the PNG_URL variable. This variable remains in installExternals.py

Here you can see it on the screenshot
![image](https://user-images.githubusercontent.com/106169496/235731053-ec6268c8-5db7-4bcd-983c-1a80f9d5f09c.png)


That fix my problen on the installation externals stage.
